version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sepsis-api
    volumes:
      - ./:/app
      - ./models:/app/models
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - sepsis-network
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: sepsis-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-sepsis_prediction}
    ports:
      - "5432:5432"
    networks:
      - sepsis-network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: sepsis-redis
    ports:
      - "6379:6379"
    networks:
      - sepsis-network
    restart: unless-stopped

networks:
  sepsis-network:
    driver: bridge

volumes:
  postgres_data:
